server:
    port: 7071
eureka:
  instance: micro-user-server
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
spring:
  application:
      name: micro-user-server

  datasource:
    url: jdbc:mysql://localhost:3306/micro-vehicle?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Wu273023136
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/in9090/user/server/*/mapping/*.xml
  type-aliases-package: classpath:com/in9090/user/server/*/entity
  configuration:
       map-underscore-to-camel-case: true
       call-setters-on-nulls: true